services:
  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  prometheus:
    image: prom/prometheus
    container_name: prometheus-server
    ports:
      - "9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  nginx:
    image: nginx:alpine
    container_name: nginx-prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./prometheus/.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - prometheus
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana-server
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
  golang-api:
    container_name: fake-store-api
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
    environment:
      - ENVIRONMENT=production
    command: [ "sh", "entrypoint.sh" ]
    depends_on:
      - redis
      - nginx
      - prometheus

volumes:
  redis-data:
    driver: local
