services:
  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  postgres:
    image: postgres:16-alpine
    container_name: postgres-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  golang-api:
    container_name: fake-store-api
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
    environment:
      - ENVIRONMENT=production
    command: [ "sh", "entrypoint.sh" ]
    depends_on:
      - postgres
      - redis

volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local
